### ISSUE TITLE
Greeting, and feedback from Nimble 👋 

### ISSUE THREAD

**Issue by sleepylee** [CharithaRatnayake/Nimble#8]
Hi Charitha,
Thanks for spending your time with us during the recruitment process. My name is Trung - an engineer from Nimble. I went through your codebase and will provide you with some feedback as below.

**What went well:**
Here are what I think you did well:
- The app is functioning as expected with the core features delivered.
- It was great that you also considered delivering optional feature requirements.
- Good attention to detail, i.e., appended character `l` to get a higher quality image to display. While it's been provided in the API document, many applicants usually miss this detail.

**What could be better:**
To name a few, here are some highlights that I think could be improved:
- Insufficient tests, including unit tests, integration tests, or UI tests.
- Release build type isn't configured correctly [without the minifyEnabled](https://github.com/CharithaRatnayake/Nimble/blob/main/app/build.gradle#L33).
- A few odd details, like: 
  - Naming [Resource1](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/data/Resource1.kt),
  - File name started without a capitalized character: [extension.kt](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/utils/extension.kt), 
  - [Having password validation on a Login flow seems odd](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/ui/auth/login/LoginFragment.kt#L75), shouldn't it be enforced during the registration only? Moreover, the validation logic is being placed on a view.
- Usage of extracted dimens, colors, style values were not consistently applied throughout the codebase, i.e., https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/res/layout/fragment_home.xml#L9, https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/res/layout/fragment_survey.xml#L72, etc...
- DataStore does not encrypt data by default, so considering [storing sensitive data like tokens without encryption](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/di/repository/UserPreferencesRepository.kt) could be dangerous.
...

I hope this feedback is helpful to you, regardless of the verdict from this challenge.

Happy coding, and best regards,
Trung.

**Comment by CharithaRatnayake** [comment]
Hi @sleepylee thanks for the review.

The issues mentioned below have been fixed, and some of them will be fixed in the meantime. Thanks

- **Release build type isn't configured correctly [without the minifyEnabled](https://github.com/CharithaRatnayake/Nimble/blob/main/app/build.gradle#L33).** - Fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/7acefabc30a101840e037fbc399723cf42d2d064.
- **Naming [Resource1](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/data/Resource1.kt),** - This file is no longer used in the project and I delete it. Fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/7acefabc30a101840e037fbc399723cf42d2d064.
- **File name started without a capitalized character: [extension.kt](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/utils/extension.kt),** - Fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/7acefabc30a101840e037fbc399723cf42d2d064.
- **Usage of extracted dimens, colors, style values were not consistently applied throughout the codebase, i.e.,** - Fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/7acefabc30a101840e037fbc399723cf42d2d064.
- **Insufficient tests, including unit tests, integration tests, or UI tests.** - IN PROGRESS _(I couldn't do much unit testing due to a limited time frame)_
- **[Having password validation on a Login flow seems odd](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/ui/auth/login/LoginFragment.kt#L75), shouldn't it be enforced during the registration only? Moreover, the validation logic is being placed on a view.**  - IN PROGRESS
- **DataStore does not encrypt data by default, so considering [storing sensitive data like tokens without encryption](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/di/repository/UserPreferencesRepository.kt) could be dangerous.** - IN PROGRESS

**Comment by CharithaRatnayake** [comment]
[Having password validation on a Login flow seems odd](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/ui/auth/login/LoginFragment.kt#L75), shouldn't it be enforced during the registration only? Moreover, the validation logic is being placed on a view.

This issue has been fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/18e36754c4bf4d5288b309d0349f67223fd36a14, 

- Auth verification business logic move to `AuthViewModel`.
- Remove 6-character password validation from the login screen and only check the `isEmpty` validation in login screen

**Comment by CharithaRatnayake** [comment]
DataStore does not encrypt data by default, so considering [storing sensitive data like tokens without encryption](https://github.com/CharithaRatnayake/Nimble/blob/main/app/src/main/java/com/nimble/di/repository/UserPreferencesRepository.kt) could be dangerous.

This issue has been fixed in the following commit https://github.com/CharithaRatnayake/Nimble/commit/e386ea26c0d1be567fd3d6553a6eb118bda47f97.

- AES Cipher encryption and decrypt.
- `AES_SECRET_KEY` and `AES_INITIALIZATION_VECTOR` added as Base64 text.
- Data store `access_token` and `refresh_token` saved as encrypted data.

**Comment by CharithaRatnayake** [comment]
Insufficient tests, including unit tests, integration tests, or UI tests.

Added some UI testing and issue fixes can be found in the following pr https://github.com/CharithaRatnayake/Nimble/commit/b92f0a042b73b0b77b3243e6c63881f278890bda.

**Comment by CharithaRatnayake** [comment]
Close the issue after merged the fixes to main branch.
